### ISSUE TITLE
Project preparation

### ISSUE THREAD

**Issue by pr130** [CorrelAid/kbtbr#1]
- [ ] check features that should be included -> create user stories, prioritize in roadmap (version?) 
- [x] zenhub 
- [x] check documentation of the API ([version 2](https://kobo.correlaid.org/api/v2/) and [version 1](https://kc.correlaid.org/api/v1/))
- [x] set up test infrastructure (test forms, test user)
- [x] create call for applications
- [x] set up package (usethis::create_package)
- [x] make a deep dive into the [crul](https://github.com/ropensci/crul) package. Assess which classes could be suitable to inherit from. In particular, `HttpClient` and `HttpResonse`. -> https://docs.ropensci.org/crul/articles/choosing-a-client.html and https://docs.ropensci.org/crul/articles/best-practices-api-packages.html , potentially https://docs.ropensci.org/crul/articles/curl-options.html#using-curl-options-in-other-packages
- [ ] draft a UML class diagram, as a guidance for the final architecture. Discuss relevant methods for each class etc.
- [ ] research packages that use R6 under the hood [`stan-dev/cmdstanr`](https://github.com/stan-dev/cmdstanr)
- [ ] check other R6 packages for best practices in terms of code structure, documentation 
- [ ] draft the authentication process

**Comment by pr130** [comment]
how far do we want to set up some initial structure of the package? e.g. an initial R6 class?

**Comment by MKyhos** [comment]
Thanks for initializing the repository! :+1: 
Prior to project roll out / call for applications, I would (additional to the points you mentioned, to which I agree upon), I would suggest to

- [ ] make a deep dive into the [crul](https://github.com/ropensci/crul) package. Assess which classes could be suitable to inherit from. In particular, `HttpClient` and `HttpResonse`.
- [ ] draft a UML class diagram, as a guidance for the final architecture. Discuss relevant methods for each class etc.
- [ ] check other R6 packages, eg. [`stan-dev/cmdstanr`](https://github.com/stan-dev/cmdstanr), for best practices in terms of code structure, documentation
- [ ] draft the authentication process

**Comment by MKyhos** [comment]
Less code-related: also preparing a brief introduction to R6, crul/Http, and object design might be beneficial for the later process. Or creating a brief project wiki that includes links to helpful resources, to support future project participants / collaborators :thinking_face:

**Comment by pr130** [comment]
thanks for the quick response. I created a test user in our instance, let me know if you want the login details to have a poke around - i'll try to create some test surveys next week or so. 

yes to the intro / wiki thing. Re package development in general, i think there are some good intro talks out there which i think we could have a small collaborative 🍿 📺  session with. I can also prepare a bit about the challenges of HTTP unit testing.

we can collect helpful resources in the wiki here (+ all in one place) or we can create a collaborative pad (+ live/collaborative, but less official and people tend to forget about their existence)

**Comment by pr130** [comment]
some thoughts regarding the features / user stories etc.:

features can be grouped / prioritized on the following dimensions 

## type of action  / asset
- list assets - meta (GET)
- download data (GET)
- upload submissions (POST)
- upload forms (POST)
- ...
## output type
- simple list (as-is)
- data frame format 
## question types
- we need to make sure that functions work for all question types 
## workflow ease
- in the beginning we could probably let the user do a lot of the work, e.g. specify the concrete asset url 
- later on, have helpers that make this easier for the user 


question is whether we implement specific user stories very well first or try to first implement a wide range of user functionality but in a basic form (e.g. only return lists for all endpoints vs very nice designed "get_form" endpoint with a good workflow)? :thinking_face:
