### ISSUE TITLE
Always make requests with trailing slash 

### ISSUE THREAD

**Issue by pr130** [CorrelAid/kbtbr#26]
from #25:

**Gotchas**
because the matching is done based comparing the URI in the yml with the URI in the _prepared_ request, it is susceptible to changes being made by the server. 
In a very annoying case, vcr gave me an error saying it could not find a matching cassette for the assets endpoint even though i had recorded it. After [enabling the vcr logs](https://books.ropensci.org/http-testing/debugging-your-tests-that-use-vcr.html#logging), i found the following line:

```
[Cassette: 'kobo-get-404'] - 2021-05-10 15:19:45 -     uri did not match: current request [get https://kobo.correlaid.org/api/v2/asset**s?**format=json] vs [get https://kobo.correlaid.org/api/v2/assets**/?**format=json]
```

Basically, whenever we make a request without a trailing `/` the kobo server will append it while processing the request, resulting in a mismatch later on when vcr tries to match the "prepared" request (without "/") with the serialized response in the yml (which has the "/" because kobo has added it). Hence, we should always pass the path with the trailing slash. I'll open a separate issue for that. 

We should investigate whether there would be any disadvantages to enforcing always making requests with a trailing "/", e.g. by checking paths with regex and optionally adding it when it is not found. 

**Related links:**

https://github.com/kobotoolbox/kpi/issues/2160
https://community.kobotoolbox.org/t/problem-using-the-new-kobo-api-cannot-post-to-create-a-new-form/6560/2

**Comment by mpadge** [comment]
No disadvantages as far as I know from enforcing trailing slash :grin:, but **lots** of disadvantages from not doing so :disappointed:, including all those typically raised by [the `urlchecker` package](https://github.com/r-lib/urlchecker/).
