### ISSUE TITLE
Manage different format responses both in Kobo$get() and KoboClient$get()

### ISSUE THREAD

**Issue by dimitri-mar** [CorrelAid/kbtbr#29]
The optional argument in query is not really helpful: if what we mean is that by default the get function should request output in JSON format, I would include it as an extra argument to the function. In fact, if a user writes a query list now, the optional format will be overridden. 
I would propose 
`function(path, query= None, version = "v2", format="json") `
and then always append to the query a format (in line 42 and 48, or before )

_Originally posted by @dimitri-mar in https://github.com/CorrelAid/kbtbr/pull/27#discussion_r633291202_

**Comment by dimitri-mar** [comment]
Moreover in KoboClient the $get method manages only JSON format.

**Comment by pr130** [comment]
note: low level methods should return the whole response.
