### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by pr130** [CorrelAid/kbtbr#3]
As a user, I want to be able to easily authenticate with the KoboToolbox API(s).

**Comment by MKyhos** [comment]
In `crul::HttpClient$new()`, we can use a `kbtbr_token` variable (holding string with the bearer token for the kobo user) for simple auth. In particular, it can be passed to the `headers` parameter like

```r
client <- crul::HttpClient$new(
   ...,
   headers = list(Authorization = paste0("Token ", kbtbr_token)
)
```

Alternatively, we could also enable simple auth via username and password (less desirable I guess?).
