### ISSUE TITLE
Code style 

### ISSUE THREAD

**Issue by pr130** [CorrelAid/kbtbr#67]
Discuss and decide upon "code style" (ha!):

- question from me: is it bad practice to use double :: notation ? :o 
- `glue` vs `sprintf` 
- `tibble` vs `data.frame`
- identation 2 vs 4 
- we could also remove some `suggests` by going through the vignettes and replacing ggplot with base plot etc.

**Comment by MKyhos** [comment]
- Regarding indentation, we agreed on 2
- I know, we did not hat the strategy to reduce dependencies on the start of the project. However, maybe in cases where something like sprintf can do the job just as well as glue, we can use it instead?
- regarding tibble, I have not a strong opinion
